# Generated by Django 4.1.7 on 2023-03-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_nuevaapp_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=16)),
                ('especialidad', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
